cargo install cargo-clippy
cargo install cargo-modules
cargo install cargo-tauri
cargo install cargo-add
cargo install cargo-fmt 
cargo install cargo-watch
cargo install cargo-rm
cargo install cargo-udeps 
cargo install cargo-create-tauri-app

cargo install bacon 
cargo install evcxr
cargo install rust-gdb
cargo install rustfmt
cargo install wasm-pack
cargo install bunyan
cargo install kondo 
cargo install rust-gdbgui
cargo install rustup 
cargo install cargo-tldr
cargo install rslint 
cargo install sqlx
