#!/bin/zsh

case "$@" in
  "aquacloud" | "aqua")
    git config user.name federico.vitale
    git config user.email federico.vitale@aquacloud.it
    ;;
  *)
    git config user.name Rawnly
    git config user.email mail@fedevitale.dev
    ;;
esac

echo "Switched to @$(git config user.name)"
